/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-background": "#d7e3fc",
        "tertiary-fixed-dim": "#b7c9d9",
        "tertiary-container": "#8193a2",
        "on-secondary-fixed-variant": "#364764",
        "outline-variant": "#414753",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#005cba",
        "primary-container": "#448ffd",
        "primary-fixed-dim": "#abc7ff",
        "error-container": "#93000a",
        "background": "#071426",
        "inverse-on-surface": "#253144",
        "on-surface": "#d7e3fc",
        "surface-bright": "#2e3a4d",
        "on-secondary-fixed": "#071c36",
        "on-primary-container": "#002959",
        "surface-container-low": "#0f1c2e",
        "on-surface-variant": "#c1c6d5",
        "on-primary-fixed-variant": "#00458e",
        "surface-tint": "#abc7ff",
        "surface": "#071426",
        "on-tertiary-fixed-variant": "#384956",
        "outline": "#8b919f",
        "tertiary-fixed": "#d3e5f6",
        "surface-variant": "#293549",
        "on-secondary-container": "#a7b9db",
        "on-primary-fixed": "#001b3f",
        "surface-container-highest": "#293549",
        "on-primary": "#002f65",
        "surface-container-lowest": "#030e20",
        "secondary": "#b5c7ea",
        "surface-dim": "#071426",
        "on-tertiary-container": "#1b2b38",
        "surface-container": "#142032",
        "primary": "#abc7ff",
        "secondary-fixed-dim": "#b5c7ea",
        "error": "#ffb4ab",
        "secondary-container": "#384a67",
        "tertiary": "#b7c9d9",
        "surface-container-high": "#1e2a3d",
        "on-secondary": "#1f314d",
        "on-tertiary-fixed": "#0c1d29",
        "inverse-surface": "#d7e3fc",
        "secondary-fixed": "#d6e3ff",
        "on-tertiary": "#21323f",
        "primary-fixed": "#d7e3ff",
        "on-error": "#690005",
        "surface-subtle": "#0a1b33",
        "surface-card": "#0d213e",
        "primary-blue": "#2F80ED",
        "primary-blue-hover": "#256ed1",
        "accent-cyan": "#60A5FA",
        "accent-soft": "#abc7ff",
        "text-main": "#F1F5F9",
        "text-muted": "#94A3B8",
        "text-dim": "#64748B",
        "border-subtle": "rgba(255, 255, 255, 0.08)",
        "border-highlight": "rgba(47, 128, 237, 0.3)"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "space-lg": "1.5rem",
        "space-md": "0.75rem",
        "space-sm": "0.5rem",
        "sidebar-width-collapsed": "4rem",
        "space-2xl": "3rem",
        "sidebar-width-expanded": "16rem",
        "space-base": "1rem",
        "gutter-compact": "0.5rem",
        "gutter-spacious": "1.5rem",
        "gutter-default": "1rem",
        "space-2xs": "0.125rem"
      },
      fontFamily: {
        "headline-xl": ["plusJakartaSans"],
        "headline-lg": ["plusJakartaSans"],
        "label-caps": ["jetbrainsMono"],
        "headline-sm": ["plusJakartaSans"],
        "data-metric-md": ["jetbrainsMono"],
        "body-sm": ["inter"],
        "body-md": ["inter"],
        "headline-md": ["plusJakartaSans"],
        "display-hero-mobile": ["plusJakartaSans"],
        "body-lg": ["inter"],
        "data-metric-sm": ["jetbrainsMono"],
        "data-metric-lg": ["jetbrainsMono"],
        "display-hero": ["plusJakartaSans"],
        sans: ["Inter", "sans-serif"],
        display: ["Plus Jakarta Sans", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        outfit: ["Outfit", "sans-serif"]
      },
      keyframes: {
        slideUpFade: {
          '0%': { opacity: 0, transform: 'translateY(20px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        }
      },
      animation: {
        'slide-up-fade': 'slideUpFade 0.4s ease-out forwards',
      }
    }
  },
  plugins: [],
}
